# jpa.hibernate.naming.physical-strategy: https://www.devglan.com/hibernate/hibernate-naming-strategy
# hibernate.dialect property makes Hibernate to generate the appropriate SQL statements for the chosen database.
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bizislife?useSSL=false
      username: stonegu
      password: stone0331
      driverClassName: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#         idleTimeout: 60000
#         minimumIdle: 2
#         maximumPoolSize: 20
#         connectionTimeout: 30000
#         poolName: MyPoolName
#         connectionTestQuery: SELECT 1        
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: true
