project:
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}
spring:
   profiles:
      active: dev
   messages:
      basename: messages/messages
      encoding: UTF-8
   jmx:
#      enabled: false
      default-domain: com.bizislife.core
      unique-names: true
   mvc:
      servlet:
         path: /api
server:
#   contextPath: /graphql
   port: 8080
clientHttp:
   timeout: 5000
---
spring.profiles: default
spring:
   profiles:
      include: jdbc,oauth2
#logging:
#   file: C:/Projects/bizMobile/logs/graphql_default.log
#   archived: C:/Projects/bizMobile/logs/archived/graphql_default-%d{yyyy-MM-dd}.%i.log
---
spring.profiles: dev
spring:
   profiles:
      include: jdbc-dev,oauth2-dev
#logging:
#   file: C:/Projects/bizMobile/logs/graphql_dev.log
#   archived: C:/Projects/bizMobile/logs/archived/graphql_dev-%d{yyyy-MM-dd}.%i.log
---
spring.profiles: qa
spring:
   profiles:
      include: jdbc-qa,oauth2-qa
#logging:
#   file: C:/Projects/bizMobile/logs/graphql_qa.log
#   archived: C:/Projects/bizMobile/logs/archived/graphql_qa-%d{yyyy-MM-dd}.%i.log
   